"""Email news digest - sends scored items to configured recipients."""

from __future__ import annotations

import json
import logging
import os
import smtplib
from datetime import date
from email.mime.multipart import MIMEMultipart
from email.mime.text import MIMEText
from pathlib import Path

logger = logging.getLogger(__name__)


def _load_candidates(path: str = "data/candidates.json") -> list[dict]:
    """Load scored candidates from the latest fetch."""
    p = Path(path)
    if not p.exists():
        return []
    try:
        return json.loads(p.read_text(encoding="utf-8"))
    except (json.JSONDecodeError, ValueError):
        return []


def _build_html_digest(items: list[dict], run_date: str) -> str:
    """Build HTML email body from scored items."""
    if not items:
        return "<p>No news items found today.</p>"

    html = f"""<html><body>
<h2>News Digest - {run_date}</h2>
<p>{len(items)} items scored and ranked.</p>
<hr>
"""
    sorted_items = sorted(items, key=lambda x: x.get("score", 0), reverse=True)

    for item in sorted_items:
        title = item.get("title", "Untitled")
        score = item.get("score", 0)
        source = item.get("feed_name", item.get("source", "Unknown"))
        link = item.get("link", item.get("url", ""))
        summary = item.get("summary", "")[:200]
        published = item.get("published", "")

        color = "#0078d4" if score >= 12 else "#ccc"
        html += f"""
<div style="margin-bottom: 16px; padding: 8px; border-left: 3px solid {color};">
  <strong><a href="{link}">{title}</a></strong> (score: {score})<br>
  <small>{source} | {published}</small><br>
  <p style="margin: 4px 0; color: #444;">{summary}</p>
</div>
"""

    html += """
<hr>
<p><small>Generated by linkedin-auto-poster</small></p>
</body></html>"""
    return html


def _build_text_digest(items: list[dict], run_date: str) -> str:
    """Build plain text email body."""
    if not items:
        return "No news items found today."

    lines = [
        f"News Digest - {run_date}",
        f"{len(items)} items",
        "=" * 40,
        "",
    ]
    sorted_items = sorted(items, key=lambda x: x.get("score", 0), reverse=True)

    for item in sorted_items:
        title = item.get("title", "Untitled")
        score = item.get("score", 0)
        link = item.get("link", item.get("url", ""))
        source = item.get("feed_name", item.get("source", "Unknown"))
        lines.append(f"[{score}] {title}")
        lines.append(f"    {source} | {link}")
        lines.append("")

    return "\n".join(lines)


def send_digest(
    candidates_path: str = "data/candidates.json",
    smtp_host: str | None = None,
    smtp_port: int = 587,
    smtp_user: str | None = None,
    smtp_pass: str | None = None,
    sender: str | None = None,
    recipients: list[str] | None = None,
) -> bool:
    """Send email digest of scored news items.

    Returns True if sent successfully, False otherwise.
    All parameters can be overridden by environment variables.
    """
    smtp_host = smtp_host or os.environ.get("SMTP_HOST")
    smtp_port = int(os.environ.get("SMTP_PORT", smtp_port))
    smtp_user = smtp_user or os.environ.get("SMTP_USERNAME")
    smtp_pass = smtp_pass or os.environ.get("SMTP_PASSWORD")
    sender = sender or os.environ.get("EMAIL_FROM", smtp_user or "")

    recipients_str = os.environ.get("EMAIL_RECIPIENTS", "")
    if not recipients:
        recipients = [r.strip() for r in recipients_str.split(",") if r.strip()]

    if not recipients:
        logger.info("No EMAIL_RECIPIENTS configured, skipping digest")
        return False

    if not smtp_host:
        logger.warning("No SMTP_HOST configured, cannot send digest")
        return False

    items = _load_candidates(candidates_path)
    run_date = str(date.today())

    html_body = _build_html_digest(items, run_date)
    text_body = _build_text_digest(items, run_date)

    msg = MIMEMultipart("alternative")
    msg["Subject"] = f"News Digest - {run_date} ({len(items)} items)"
    msg["From"] = sender
    msg["To"] = ", ".join(recipients)

    msg.attach(MIMEText(text_body, "plain"))
    msg.attach(MIMEText(html_body, "html"))

    try:
        with smtplib.SMTP(smtp_host, smtp_port, timeout=30) as server:
            server.starttls()
            if smtp_user and smtp_pass:
                server.login(smtp_user, smtp_pass)
            server.sendmail(sender, recipients, msg.as_string())
        logger.info("Digest sent to %s (%d items)", ", ".join(recipients), len(items))
        return True
    except Exception as e:
        logger.error("Failed to send digest: %s", e)
        return False
